# Generated by Django 4.2.8 on 2024-01-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Payment method name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/payment_method_images', verbose_name='Payment method logo')),
                ('language_key', models.CharField(max_length=255, null=True, verbose_name='Payment method language key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Payment method created at')),
            ],
            options={
                'verbose_name': 'Payment method',
                'verbose_name_plural': 'Payment methods',
            },
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sector name')),
                ('language_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sectors language key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sector created at')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
    ]
