# Generated by Django 4.2.8 on 2024-01-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_store_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Boutique', 'verbose_name_plural': 'Boutiques'},
        ),
    ]
