# Generated by Django 4.2.8 on 2024-01-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0005_alter_user_gender_alter_user_profil_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil_type',
            field=models.CharField(default='USER', max_length=255, verbose_name='type de profil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='venndor_authorized',
            field=models.BooleanField(default=False, verbose_name='vendeur autorisé  ?'),
        ),
    ]
