# Generated by Django 4.2.8 on 2024-01-09 14:00

import agrijeune.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0006_alter_user_profil_type_alter_user_venndor_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user_images', validators=[agrijeune.validators.valideta_image_size, agrijeune.validators.validate_image_extension], verbose_name='photo de profil'),
        ),
    ]
