# Generated by Django 4.2.8 on 2024-01-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Is main product image')),
                ('image', models.ImageField(upload_to='uploads/product_images', verbose_name='Product image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Product image created at')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
            },
        ),
    ]
